/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MeowbiusPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/view.ts
var import_obsidian2 = require("obsidian");

// src/model.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var STATUSES = ["\u524D\u671F\u51C6\u5907", "\u53E3\u55E8\u4E2D", "\u586B\u5751\u4E2D", "\u5DF2\u5B8C\u6210"];
var STANDARD = [
  "00_\u4E16\u754C\u89C2\u8BBE\u5B9A",
  "01_\u65F6\u95F4\u8F74",
  "02_\u4EBA\u7269",
  "03_\u53EA\u8A00\u7247\u8BED",
  "04_\u7247\u6BB5\u53E3\u55E8",
  "05_\u5DF2\u6574\u7406",
  "06_\u884D\u751F\u8111\u6D1E"
];
var INSP_SUBFOLDERS = ["\u8111\u6D1E", "\u5927\u7EB2", "\u53EA\u8A00\u7247\u8BED", "\u77E5\u8BC6\u8865\u5145"];
var TPL_FILE = {
  brain: "\u8111\u6D1E\u5361\u6A21\u677F.md",
  frag: "\u53EA\u8A00\u7247\u8BED\u6A21\u677F.md",
  gen: "\u901A\u7528\u7B14\u8BB0\u6A21\u677F.md"
};
var TPL_TYPES = [
  { k: "brain", label: "\u8111\u6D1E\u5361" },
  { k: "frag", label: "\u53EA\u8A00\u7247\u8BED" },
  { k: "gen", label: "\u901A\u7528\u7B14\u8BB0" }
];
var TEMPLATE_LIBRARY = "\u6A21\u677F\u5E93";
function todayStr() {
  const d = /* @__PURE__ */ new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate()
  ).padStart(2, "0")}`;
}
function tplContent(type) {
  const d = todayStr();
  if (type === "brain")
    return `---
type: \u8111\u6D1E
status: \u524D\u671F\u51C6\u5907
tags: []
created: ${d}
\u65F6\u95F4: 
\u7075\u611F\u6765\u6E90: 
\u6838\u5FC3\u6982\u5FF5: 
\u5173\u8054\u8111\u6D1E: 
---

# \u8111\u6D1E\u6807\u9898

`;
  if (type === "frag")
    return `---
type: \u788E\u7247
created: ${d}
\u65F6\u95F4: 
\u7075\u611F\u6765\u6E90: 
tags: []
---

`;
  return `---
type: \u7B14\u8BB0
created: ${d}
\u65F6\u95F4: 
\u7075\u611F\u6765\u6E90: 
---

`;
}
function templateTypeFor(sub) {
  if (sub === "\u8111\u6D1E" || sub === "\u884D\u751F\u8111\u6D1E") return "brain";
  if (sub === "\u53EA\u8A00\u7247\u8BED") return "frag";
  return "gen";
}
function normalizeName(s) {
  return s.replace(/^\d+[._\-\s]*/, "").replace(/(设定|笔记|资料|文件夹|稿|doc|note)$/i, "").trim();
}
function isTypeFolder(name) {
  return /^\d+_/.test(name);
}

// src/model.ts
function findNode(model, path) {
  return model.map.get(path);
}
function yearWords(node, year) {
  if (node.type === "note") {
    return node.mtime && new Date(node.mtime).getFullYear() === year ? node.words : 0;
  }
  let s = 0;
  for (const c of node.children || []) s += yearWords(c, year);
  return s;
}
function spaceTypes(node) {
  return (node.children || []).filter(
    (c) => c.type === "folder" && isTypeFolder(c.name)
  );
}
function scopeStats(space, statScope) {
  let w = 0, n = 0, y = 0;
  const year = (/* @__PURE__ */ new Date()).getFullYear();
  const excl = statScope.map(normalizeName);
  for (const ch of space.children || []) {
    if (ch.type === "folder" && isTypeFolder(ch.name) && (excl.length === 0 || !excl.includes(normalizeName(ch.name)))) {
      w += ch.words;
      n += ch.notes;
      y += yearWords(ch, year);
    }
  }
  return { w, n, y };
}
function collectCharacters(model, statScope) {
  const charCore = normalizeName(STANDARD[2]);
  const excl = statScope.map(normalizeName);
  if (excl.length > 0 && excl.includes(charCore)) return [];
  const map = {};
  for (const s of model.spaces) {
    const pf = s.children?.find(
      (f) => f.type === "folder" && normalizeName(f.name) === charCore
    );
    if (!pf) continue;
    for (const n of pf.children || []) {
      if (n.type === "note") {
        const k = n.name.replace(/\.md$/, "");
        map[k] = (map[k] || 0) + n.words;
      }
    }
  }
  return Object.entries(map).map(([name, w]) => ({ name, w })).sort((a, b) => b.w - a.w);
}
function computeAggregates(node) {
  if (node.type === "note") return;
  let w = 0, n = 0;
  for (const c of node.children || []) {
    computeAggregates(c);
    w += c.words;
    n += c.notes;
  }
  node.words = w;
  node.notes = n;
}
function collectNotes(node, acc) {
  if (node.type === "note") {
    acc.push(node);
    return;
  }
  for (const c of node.children || []) collectNotes(c, acc);
}
async function buildModel(app, rootName) {
  const files = app.vault.getAllLoadedFiles();
  const map = /* @__PURE__ */ new Map();
  const root = {
    name: "",
    path: "",
    type: "folder",
    children: [],
    words: 0,
    notes: 0
  };
  const notes = [];
  for (const f of files) {
    if (f instanceof import_obsidian.TFolder) {
      map.set(f.path, {
        name: f.name,
        path: f.path,
        type: "folder",
        children: [],
        words: 0,
        notes: 0
      });
    } else if (f instanceof import_obsidian.TFile) {
      const cache = app.metadataCache.getFileCache(f);
      const fm = cache?.frontmatter;
      const node = {
        name: f.name,
        path: f.path,
        type: "note",
        words: 0,
        notes: 1,
        status: typeof fm?.status === "string" ? fm.status : void 0,
        date: typeof fm?.date === "string" ? fm.date : void 0,
        created: f.stat.ctime,
        mtime: f.stat.mtime
      };
      map.set(f.path, node);
      notes.push(node);
    }
  }
  for (const [path, node] of map) {
    if (!path) continue;
    const slash = path.lastIndexOf("/");
    const parentPath = slash >= 0 ? path.slice(0, slash) : "";
    const parent = map.get(parentPath) || root;
    parent.children.push(node);
  }
  const inspRoot = root.children?.find(
    (c) => c.name === rootName && c.type === "folder"
  );
  const library = root.children?.find(
    (c) => c.name === TEMPLATE_LIBRARY && c.type === "folder"
  );
  const spaces = (root.children || []).filter(
    (c) => c.type === "folder" && c.name !== rootName && c.name !== TEMPLATE_LIBRARY
  );
  const relevant = [inspRoot, library, ...spaces].filter(
    (n) => !!n
  );
  const toRead = [];
  for (const r of relevant) collectNotes(r, toRead);
  await Promise.all(
    toRead.map(async (node) => {
      const file = app.vault.getAbstractFileByPath(node.path);
      if (file instanceof import_obsidian.TFile) {
        try {
          const content = await app.vault.cachedRead(file);
          node.words = content.replace(/\s/g, "").length;
        } catch {
          node.words = 0;
        }
      }
    })
  );
  computeAggregates(root);
  return { root, map, rootName, inspRoot, library, spaces };
}

// src/view.ts
var VIEW_TYPE = "meowbius-kanban-view";
function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function spaceTimes(node) {
  let created;
  let mtime;
  const walk = (n) => {
    if (n.type === "note") {
      if (n.created !== void 0)
        created = created === void 0 ? n.created : Math.min(created, n.created);
      if (n.mtime !== void 0)
        mtime = mtime === void 0 ? n.mtime : Math.max(mtime, n.mtime);
    } else {
      for (const c of n.children || []) walk(c);
    }
  };
  walk(node);
  return { created, mtime };
}
var KanbanView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.kanbanTab = "overview";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Meowbius_S.S";
  }
  getIcon() {
    return "layout-grid";
  }
  /** 取得本插件 icons/ 目录下资源的可用 URL（跟随插件部署，不依赖外部路径） */
  iconUrl(name) {
    const id = this.plugin.manifest.id;
    const rel = `${this.app.vault.configDir}/plugins/${id}/icons/${name}`;
    return this.app.vault.adapter.getResourcePath(rel);
  }
  async onOpen() {
    await this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  async render() {
    const model = this.plugin.model || await this.plugin.refreshModel();
    const root = this.contentEl;
    root.empty();
    root.addClass("mb-view");
    const kanban = root.createDiv({ cls: "mb-kanban" });
    kanban.innerHTML = this.kanbanHTML(model);
    this.wire(kanban);
    await this.fillTimeline(kanban);
  }
  /* ---------- 页签与排序 ---------- */
  defaultOrder(model) {
    const spaces = model.spaces.map((s) => s.name);
    return ["overview", ...spaces, "\u7075\u611F\u6536\u96C6", "\u6A21\u677F\u5E93"];
  }
  syncOrder(model) {
    const expected = this.defaultOrder(model);
    const order = this.plugin.settings.kanbanOrder;
    const kept = order.filter((id) => expected.includes(id));
    const missing = expected.filter((id) => !kept.includes(id));
    const idx = kept.lastIndexOf("\u7075\u611F\u6536\u96C6");
    let next;
    if (idx >= 0) {
      next = [...kept];
      next.splice(idx + 1, 0, ...missing);
    } else {
      next = [...kept, ...missing];
    }
    if (next.join("|") !== order.join("|")) {
      this.plugin.settings.kanbanOrder = next;
      void this.plugin.saveSettings();
    }
  }
  tabLabel(id) {
    if (id === "overview") return "\u{1F4CA} \u603B\u4F53";
    if (id === "\u7075\u611F\u6536\u96C6") return "\u{1F4E5} \u7075\u611F\u6536\u96C6";
    if (id === "\u6A21\u677F\u5E93") return "\u{1F4DA} \u6A21\u677F\u5E93";
    return "\u2728 " + id;
  }
  kt(id, label) {
    return `<div class="ktab ${this.kanbanTab === id ? "active" : ""}" data-k="${esc(id)}">${label}</div>`;
  }
  /* ---------- 总装 ---------- */
  kanbanHTML(model) {
    this.syncOrder(model);
    const visible = this.plugin.settings.kanbanOrder.filter(
      (id) => !this.plugin.settings.kanbanHidden[id]
    );
    let t = `<div class="ktabs">`;
    visible.forEach((id) => {
      t += this.kt(id, this.tabLabel(id));
    });
    const icSet = this.iconUrl("setting.svg");
    const icSync = this.iconUrl("sync.svg");
    t += `<div class="ktab-sep"></div><div class="kacts">`;
    t += `<div class="kact" data-global-refresh title="\u5237\u65B0\u5168\u90E8\u6570\u636E"><span class="mb-icon" style="--mb-mask:url('${icSync}')"></span></div>`;
    t += `<div class="kact ${this.kanbanTab === "config" ? "active" : ""}" data-k="config" title="\u770B\u677F\u914D\u7F6E\uFF08\u987A\u5E8F / \u663E\u9690 / \u7EDF\u8BA1\u8303\u56F4 / \u6587\u4EF6\u5939\u6620\u5C04\uFF09"><span class="mb-icon" style="--mb-mask:url('${icSet}')"></span></div>`;
    t += `</div></div>`;
    if (this.kanbanTab === "overview") t += this.overviewHTML(model);
    else if (this.kanbanTab === "\u7075\u611F\u6536\u96C6") t += this.inspirationHTML(model);
    else if (this.kanbanTab === "\u6A21\u677F\u5E93") t += this.templateBoardHTML(model);
    else if (this.kanbanTab === "config") t += this.configHTML(model);
    else t += this.entityHTML(model, this.kanbanTab);
    return t;
  }
  /* ---------- 总览 ---------- */
  overviewHTML(model) {
    const scope = this.plugin.settings.statScope;
    const spaces = model.spaces;
    const totalPits = spaces.length;
    const stCount = {};
    STATUSES.forEach((s) => stCount[s] = 0);
    spaces.forEach((s) => {
      const st = this.plugin.settings.spaceStatus[s.name] || "\u524D\u671F\u51C6\u5907";
      stCount[st] = (stCount[st] || 0) + 1;
    });
    const rows = spaces.map((s) => {
      const st = scopeStats(s, scope);
      return { name: s.name, w: st.w, n: st.n, y: st.y };
    });
    const totalWords = rows.reduce((a, r) => a + r.w, 0);
    const totalYear = rows.reduce((a, r) => a + r.y, 0);
    const totalNotes = rows.reduce((a, r) => a + r.n, 0);
    const chars = collectCharacters(model, scope);
    let h = `<div class="ksec"><h3 class="board-title">\u{1F4CA} \u603B\u4F53\u7EDF\u8BA1</h3><div class="stat-grid">
      <div class="stat-card"><div class="big">${totalPits}</div><div class="lbl">\u603B\u5751\u6570\uFF08\u8111\u6D1E\u7A7A\u95F4\uFF09</div></div>
      <div class="stat-card"><div class="big">${totalWords}</div><div class="lbl">\u603B\u5B57\u6570</div><div class="sub">\u4ECA\u5E74\u66F4\u65B0 ${totalYear}</div></div>
    </div></div>`;
    h += `<div class="ksec"><h3>\u{1F573}\uFE0F \u5404\u72B6\u6001\u5751\u4E2A\u6570</h3><div class="chips">`;
    STATUSES.forEach((s) => h += `<div class="chip"><b>${stCount[s]}</b>${s}</div>`);
    h += `</div></div>`;
    h += `<div class="ksec"><h3>\u{1F4DD} \u603B\u5B57\u6570\u53CA\u5404\u5751\u5360\u6BD4</h3>`;
    if (!rows.length) h += `<p class="muted">\u6682\u65E0\u8111\u6D1E\u7A7A\u95F4\u3002</p>`;
    else {
      h += `<div class="scope-grid">`;
      rows.forEach((r) => {
        const wp = totalWords ? Math.round(r.w / totalWords * 100) : 0;
        const np = totalNotes ? Math.round(r.n / totalNotes * 100) : 0;
        h += `<div class="scope-card"><div class="scope-card-name">${esc(r.name)}</div><div class="scope-card-big">${r.w}<span class="scope-card-unit">\u5B57</span></div><div class="scope-card-meta">\u5360\u6BD4 ${wp}% \xB7 ${r.n} \u4E2A\u6587\u4EF6 \xB7 \u5360\u6BD4 ${np}%</div><div class="bar"><div class="bar-fill" style="width:${wp}%"></div></div></div>`;
      });
      h += `</div>`;
    }
    h += `</div>`;
    h += `<div class="ksec"><h3>\u{1F4C5} \u4ECA\u5E74\u66F4\u65B0\u5B57\u6570\u53CA\u5404\u5751\u5360\u6BD4</h3>`;
    if (!rows.length) h += `<p class="muted">\u6682\u65E0\u8111\u6D1E\u7A7A\u95F4\u3002</p>`;
    else {
      h += `<div class="scope-grid">`;
      rows.forEach((r) => {
        const yp = totalYear ? Math.round(r.y / totalYear * 100) : 0;
        const np = totalNotes ? Math.round(r.n / totalNotes * 100) : 0;
        h += `<div class="scope-card"><div class="scope-card-name">${esc(r.name)}</div><div class="scope-card-big">${r.y}<span class="scope-card-unit">\u5B57</span></div><div class="scope-card-meta">\u5360\u6BD4 ${yp}% \xB7 ${r.n} \u4E2A\u6587\u4EF6 \xB7 \u5360\u6BD4 ${np}%</div><div class="bar"><div class="bar-fill" style="width:${yp}%"></div></div></div>`;
      });
      h += `</div>`;
    }
    h += `</div>`;
    h += `<div class="ksec"><h3>\u{1F465} \u89D2\u8272\u8BCD\u4E91\uFF08\u53D6\u81EA\u5404\u8111\u6D1E\u300C${normalizeName(
      STANDARD[2]
    )}\u300D\u6587\u4EF6\u5939\uFF09</h3>`;
    if (!chars.length) {
      h += `<p class="muted">\u5F53\u524D\u7EDF\u8BA1\u8303\u56F4\u672A\u5305\u542B\u300C${normalizeName(
        STANDARD[2]
      )}\u300D\uFF0C\u6682\u65E0\u53EF\u5C55\u793A\u7684\u89D2\u8272\u8BCD\u4E91\u3002</p></div>`;
    } else {
      h += `<div class="cloud">`;
      chars.forEach((ch) => {
        const size = 15 + Math.min(22, Math.floor(ch.w / 12));
        h += `<span style="font-size:${size}px">${esc(ch.name)}</span>`;
      });
      h += `</div></div>`;
    }
    return h;
  }
  /* ---------- 单脑洞：三个堆叠模块 ---------- */
  entityHTML(model, name) {
    const node = model.spaces.find((s) => s.name === name);
    if (!node)
      return `<p class="muted">\u672A\u627E\u5230\u8111\u6D1E\u7A7A\u95F4\u300C${esc(name)}\u300D\u3002</p>`;
    let h = "";
    h += this.entityBasicInfo(node);
    h += this.entityOverview(node);
    h += this.heatmapSection(node.path + "/", "\u{1F525} \u6D3B\u8DC3\u70ED\u529B\u56FE\uFF08\u8FD1 12 \u4E2A\u6708\uFF09");
    h += `<div class="ksec entity-mod" data-tlspace="${esc(
      node.path
    )}"><h3 class="mod-title">\u{1F570}\uFE0F \u65F6\u95F4\u8F74</h3><div class="tl-body"><div class="tl-loading">\u52A0\u8F7D\u4E2D\u2026</div></div></div>`;
    return h;
  }
  /** 模块 1：基本信息（创建时间 / 最近更新 / 总字数 / 总文件数 / 状态） */
  entityBasicInfo(node) {
    const t = spaceTimes(node);
    const created = t.created ? new Date(t.created).toLocaleString("zh-CN") : "\u2014";
    const mtime = t.mtime ? new Date(t.mtime).toLocaleString("zh-CN") : "\u2014";
    const cur = this.plugin.settings.spaceStatus[node.name] || STATUSES[0];
    let pills = "";
    STATUSES.forEach((s) => {
      pills += `<span class="st-pill ${cur === s ? "active" : ""}" data-spacestatus="${esc(s)}" data-spacename="${esc(node.name)}">${esc(s)}</span>`;
    });
    return `<div class="ksec entity-mod">
      <h3 class="mod-title">\u{1F4CB} \u57FA\u672C\u4FE1\u606F</h3>
      <div class="info-grid">
        <div class="info-item"><span class="info-k">\u{1F5D3}\uFE0F \u521B\u5EFA\u65F6\u95F4</span><span class="info-v">${created}</span></div>
        <div class="info-item"><span class="info-k">\u{1F504} \u6700\u8FD1\u66F4\u65B0</span><span class="info-v">${mtime}</span></div>
        <div class="info-item"><span class="info-k">\u{1F4DD} \u603B\u5B57\u6570</span><span class="info-v">${node.words}</span></div>
        <div class="info-item"><span class="info-k">\u{1F4C1} \u603B\u6587\u4EF6\u6570</span><span class="info-v">${node.notes}</span></div>
      </div>
      <div class="status-row">
        <span class="status-label">\u{1F4CC} \u5F53\u524D\u72B6\u6001</span>
        <span class="status-pills">${pills}</span>
      </div>
    </div>`;
  }
  /** 模块 2：速览（仅展示「数字_文字」类型子文件夹；不符合规则时给出说明性空态） */
  entityOverview(node) {
    const all = (node.children || []).filter((c) => c.type === "folder");
    const shown = all.filter((c) => isTypeFolder(c.name));
    let h = `<div class="ksec entity-mod"><h3 class="mod-title">\u26A1 \u901F\u89C8</h3>`;
    if (shown.length) {
      h += this.renderSubCards(node, false);
    } else {
      h += `<div class="eempty">
        <div class="ee-main">\u8BE5\u8111\u6D1E\u4E0B\u6682\u65E0\u300C\u6570\u5B57_\u6587\u5B57\u300D\u683C\u5F0F\u7684\u5C55\u793A\u578B\u5B50\u6587\u4EF6\u5939\u3002</div>
        <div class="ee-sub">\u5F53\u524D\u5171\u6709 ${all.length} \u4E2A\u5B50\u6587\u4EF6\u5939\uFF0C\u5176\u4E2D ${shown.length} \u4E2A\u7B26\u5408\u5C55\u793A\u89C4\u5219\uFF08\u547D\u540D\u5F62\u5982 00_\u4E16\u754C\u89C2\u8BBE\u5B9A\uFF09\u3002\u975E\u7C7B\u578B\u6587\u4EF6\u5939\u4E0D\u4F1A\u51FA\u73B0\u5728\u770B\u677F\u4E2D\u3002</div>
      </div>`;
    }
    h += `</div>`;
    return h;
  }
  /** 子文件夹卡片（速览 / 灵感收集共用）：文件数 + 字数 + 点击新建；showLocate 控制是否显示「定位」按钮 */
  renderSubCards(node, showLocate, filterByType = true) {
    const kids = (node.children || []).filter(
      (c) => c.type === "folder" && (!filterByType || isTypeFolder(c.name))
    );
    if (!kids.length) return "";
    let h = `<div class="card-grid">`;
    for (const ch of kids) {
      const cp = ch.path;
      h += `<div class="type-card" data-newfile="${esc(cp)}">
        ${showLocate ? `<button class="loc" data-focus="${esc(cp)}" title="\u5728\u6587\u4EF6\u680F\u5B9A\u4F4D">\u{1F4C2}</button>` : ""}
        <div class="tc-name">${esc(ch.name)}</div>
        <div class="tc-meta"><span class="tc-num">${ch.notes}</span> \u4E2A\u6587\u4EF6 \xB7 ${ch.words} \u5B57</div>
        <div class="tc-add">\uFF0B \u70B9\u51FB\u65B0\u5EFA\u7B14\u8BB0</div>
      </div>`;
    }
    h += `</div>`;
    return h;
  }
  /* ---------- 文件夹信息 / 子文件夹卡片配置 ---------- */
  folderMetaHTML(node) {
    const t = spaceTimes(node);
    const created = t.created ? new Date(t.created).toLocaleDateString("zh-CN") : "\u2014";
    const mtime = t.mtime ? new Date(t.mtime).toLocaleDateString("zh-CN") : "\u2014";
    return `<div class="ksec"><h3>\u{1F4C1} \u6587\u4EF6\u5939\u4FE1\u606F</h3>
      <div class="meta-grid">
        <div class="meta-row"><span class="meta-k">\u{1F5D3}\uFE0F \u521B\u5EFA\u65F6\u95F4</span><span class="meta-v">${created}</span></div>
        <div class="meta-row"><span class="meta-k">\u{1F504} \u6700\u8FD1\u66F4\u65B0</span><span class="meta-v">${mtime}</span></div>
      </div></div>`;
  }
  /* ---------- 灵感收集 ---------- */
  inspirationHTML(model) {
    const root = model.inspRoot;
    if (!root)
      return `<p class="muted">\u672A\u627E\u5230\u300C${esc(model.rootName)}\u300D\u6839\u76EE\u5F55\u3002</p>`;
    return `<div class="ksec"><h3 class="board-title">\u{1F4E5} \u7075\u611F\u6536\u96C6</h3>` + this.folderMetaHTML(root) + this.renderSubCards(root, true, false) + `</div>` + this.heatmapSection(root.path + "/", "\u{1F525} \u7075\u611F\u6536\u96C6\u6D3B\u8DC3\u70ED\u529B\u56FE\uFF08\u8FD1 12 \u4E2A\u6708\uFF09");
  }
  /* ---------- 模板库看板 ---------- */
  templateBoardHTML(model) {
    const targets = [];
    if (model.inspRoot) targets.push(model.inspRoot);
    targets.push(...model.spaces);
    let h = `<div class="tpl-sec"><div class="ksec"><h3 class="board-title">\u{1F4DA} \u6A21\u677F\u5E93\u770B\u677F</h3>`;
    if (model.library) h += this.folderMetaHTML(model.library);
    h += `<div class="tpl-grid">
        <div class="tpl-row tpl-head"><div class="tpl-name">\u76EE\u5F55 \uFF3C \u6A21\u677F</div>`;
    TPL_TYPES.forEach((t) => h += `<div class="tpl-colhead">${t.label}</div>`);
    h += `</div>`;
    for (const space of targets) {
      h += `<div class="tpl-row"><div class="tpl-name" title="${esc(
        space.name
      )}">${esc(space.name)}</div>`;
      for (const t of TPL_TYPES) {
        const path = `${space.path}/\u6A21\u677F/${TPL_FILE[t.k]}`;
        const node = this.plugin.nodeByPath(path);
        const exists = node && node.type === "note";
        const hasContent = !!exists && node.words > 0;
        let cls, act, tip;
        if (!exists) {
          cls = "tpl-off";
          act = `data-needtpl="${esc(path)}"`;
          tip = `${space.name} \xB7 ${t.label}\u6A21\u677F\uFF08\u7F3A\u5931\uFF0C\u70B9\u51FB\u65B0\u5EFA\uFF09`;
        } else if (hasContent) {
          cls = "tpl-on";
          act = `data-tpledit="${esc(path)}"`;
          tip = `${space.name} \xB7 ${t.label}\u6A21\u677F\uFF08\u70B9\u51FB\u7F16\u8F91\uFF09`;
        } else {
          cls = "tpl-empty";
          act = `data-tpledit="${esc(path)}"`;
          tip = `${space.name} \xB7 ${t.label}\u6A21\u677F\uFF08\u5B58\u5728\u4F46\u4E3A\u7A7A\uFF0C\u70B9\u51FB\u7F16\u8F91\uFF09`;
        }
        h += `<div class="tpl-cell ${cls}" ${act} title="${esc(tip)}"></div>`;
      }
      h += `</div>`;
    }
    h += `</div>
      <div class="tpl-legend">
        <span><span class="sq" style="background:var(--mb-green)"></span>\u5DF2\u5B58\u5728\u4E14\u6709\u5185\u5BB9</span>
        <span><span class="sq" style="background:var(--mb-orange)"></span>\u5B58\u5728\u4F46\u4E3A\u7A7A</span>
        <span><span class="sq" style="background:#5a3a3e"></span>\u7F3A\u5931\uFF08\u70B9\u51FB\u65B0\u5EFA\uFF09</span>
      </div>
    </div></div>`;
    return h;
  }
  /* ---------- 配置 ---------- */
  configHTML(model) {
    const order = this.plugin.settings.kanbanOrder;
    const hidden = this.plugin.settings.kanbanHidden;
    let h = `<div class="ksec"><h3 class="board-title">\u2699\uFE0F \u770B\u677F\u914D\u7F6E</h3><div class="cfgtab-list">`;
    order.forEach((id, i) => {
      const label = this.tabLabel(id);
      const isHidden = hidden[id];
      h += `<div class="cfgtab ${isHidden ? "off" : ""}" draggable="true" data-drag="${esc(
        id
      )}">
        <span class="ct-name"><span class="ct-handle">\u2630</span>${esc(
        label
      )}</span>
        <span class="ct-act">
          <button class="mb-btn tiny" data-move="${esc(
        id
      )}" data-dir="up" ${i === 0 ? "disabled" : ""}>\u2191 \u4E0A\u79FB</button>
          <button class="mb-btn tiny" data-move="${esc(
        id
      )}" data-dir="down" ${i === order.length - 1 ? "disabled" : ""}>\u2193 \u4E0B\u79FB</button>
          <button class="mb-btn tiny" data-hide="${esc(
        id
      )}">${isHidden ? "\u663E\u793A" : "\u9690\u85CF"}</button>
        </span>
      </div>`;
    });
    h += `</div>`;
    h += `<div class="ksec"><h3>\u{1F4CA} \u7EDF\u8BA1\u8303\u56F4</h3><div class="scope-tags">`;
    const excl = this.plugin.settings.statScope;
    this.plugin.allTypeNames().forEach((t) => {
      const active = excl.length === 0 || !excl.includes(t);
      h += `<span class="scope-tag ${active ? "active" : ""}" data-scope="${esc(t)}">${esc(t)}</span>`;
    });
    h += `</div></div>`;
    h += `<div class="ksec"><h3>\u{1F9ED} \u6587\u4EF6\u5939\u6620\u5C04</h3><button class="mb-btn primary" data-adopt>\u{1F504} \u6620\u5C04\u6587\u4EF6\u5939</button></div>`;
    h += `</div>`;
    return h;
  }
  /* ---------- 热力图（通用，按 prefix 限定子树） ---------- */
  heatmapSection(prefix, title) {
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const start = new Date(today);
    start.setDate(start.getDate() - 363);
    const sd = start.getDay();
    start.setDate(start.getDate() - sd);
    const days = [];
    const cur = new Date(start);
    while (cur <= today) {
      days.push(new Date(cur));
      cur.setDate(cur.getDate() + 1);
    }
    const cols = Math.ceil(days.length / 7);
    const MON = [
      "1\u6708",
      "2\u6708",
      "3\u6708",
      "4\u6708",
      "5\u6708",
      "6\u6708",
      "7\u6708",
      "8\u6708",
      "9\u6708",
      "10\u6708",
      "11\u6708",
      "12\u6708"
    ];
    const labels = new Array(cols).fill("");
    const map = this.plugin.heatmapMap(prefix);
    let maxv = 0;
    for (const d of days) {
      const v = map.get(`${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`) || 0;
      if (v > maxv) maxv = v;
    }
    const cells = [];
    days.forEach((d, i) => {
      const col = Math.floor(i / 7);
      const key = `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`;
      const v = map.get(key) || 0;
      const lvl = maxv > 0 ? Math.min(4, Math.ceil(v / maxv * 4)) : 0;
      if (i % 7 === 0) {
        const m = MON[d.getMonth()];
        if (col === 0) labels[col] = m;
        else if (days[(col - 1) * 7].getMonth() !== d.getMonth())
          labels[col] = m;
      }
      cells.push(
        `<div class="hm-cell lvl${lvl}" title="${key}${v ? "\uFF1A" + v + " \u5B57" : ""}"></div>`
      );
    });
    const labelsHTML = labels.map((m) => `<span class="hm-ml">${m}</span>`).join("");
    const hint = map.size === 0 ? `<p class="muted">\u6682\u65E0\u6D3B\u52A8\u6570\u636E\u3002</p>` : "";
    return `<div class="ksec entity-mod"><h3 class="mod-title">${title}</h3>
      ${hint}
      <div class="hm-scroll" id="hmScroll"><div class="hm-inner">
        <div class="hm-labels">${labelsHTML}</div>
        <div class="hm-grid">${cells.join("")}</div>
      </div></div>
      <div class="hm-legend"><span>\u5C11</span><span class="hm-cell lvl0"></span><span class="hm-cell lvl1"></span><span class="hm-cell lvl2"></span><span class="hm-cell lvl3"></span><span class="hm-cell lvl4"></span><span>\u591A</span></div>
    </div>`;
  }
  /* ---------- 时间轴（模块 4，异步加载） ---------- */
  async fillTimeline(kanban) {
    if (this.kanbanTab === "config" || this.kanbanTab === "overview" || this.kanbanTab === "\u7075\u611F\u6536\u96C6" || this.kanbanTab === "\u6A21\u677F\u5E93") return;
    const box = kanban.querySelector("[data-tlspace]");
    if (!box) return;
    const spacePath = box.dataset.tlspace;
    const body = box.querySelector(".tl-body");
    if (!body) return;
    const entries = await this.plugin.loadTimelineEntries(spacePath);
    body.innerHTML = this.timelineNodesHTML(entries, spacePath);
    this.bindTimeline(box, spacePath);
  }
  timelineNodesHTML(entries, spacePath) {
    let h = `<button class="mb-btn primary tl-new" data-tlnew="${esc(
      spacePath
    )}">\uFF0B \u65B0\u589E\u65F6\u95F4\u8282\u70B9</button>`;
    if (!entries.length) {
      h += `<div class="tl-empty">\u8BE5\u8111\u6D1E\u7684\u300C\u65F6\u95F4\u8F74\u300D\u6587\u4EF6\u5939\u6682\u65E0\u8282\u70B9\u3002\u70B9\u51FB\u4E0A\u65B9\u6309\u94AE\u65B0\u589E\uFF0C\u6216\u786E\u8BA4\u662F\u5426\u5B58\u5728\u300C01_\u65F6\u95F4\u8F74\u300D\u6587\u4EF6\u5939\u3002</div>`;
      return h;
    }
    h += `<div class="tl-list">`;
    for (const e of entries) {
      const date = new Date(e.mtime).toLocaleDateString("zh-CN");
      h += `<div class="tl-node" data-tlpath="${esc(e.path)}">
        <div class="tl-dot"></div>
        <div class="tl-card">
          <div class="tl-head">
            <span class="tl-title" data-tlopen="${esc(e.path)}" title="\u5728\u7F16\u8F91\u5668\u6253\u5F00">${esc(
        e.title
      )}</span>
            <span class="tl-actions">
              <button class="tl-btn" data-tledit="${esc(
        e.path
      )}" title="\u5FEB\u901F\u7F16\u8F91">\u270F\uFE0F</button>
            </span>
          </div>
          <div class="tl-snippet">${e.snippet ? esc(e.snippet) : '<span class="muted">(\u7A7A)</span>'}</div>
          <div class="tl-meta">${e.words} \u5B57 \xB7 \u66F4\u65B0\u4E8E ${date}</div>
        </div>
      </div>`;
    }
    h += `</div>`;
    return h;
  }
  bindTimeline(box, _spacePath) {
    box.querySelectorAll("[data-tlnew]").forEach((el) => {
      el.onclick = () => void this.plugin.quickCreateTimeline(el.dataset.tlnew);
    });
    box.querySelectorAll("[data-tlopen]").forEach((el) => {
      el.onclick = () => this.plugin.openFilePath(el.dataset.tlopen);
    });
    box.querySelectorAll("[data-tledit]").forEach((el) => {
      el.onclick = () => void this.beginInlineEdit(el.dataset.tledit);
    });
  }
  // 内联编辑：把节点卡片替换为 textarea，保存走 vault.modify
  async beginInlineEdit(path) {
    const node = Array.from(
      this.contentEl.querySelectorAll(".tl-node")
    ).find((n) => n.dataset.tlpath === path);
    if (!node) return;
    const card = node.querySelector(".tl-card");
    if (!card) return;
    const content = await this.plugin.readNote(path);
    card.innerHTML = `<textarea class="tl-edit" data-tltext>${esc(
      content
    )}</textarea><div class="tl-edit-bar">
      <button class="mb-btn primary" data-tlsave="${esc(
      path
    )}">\u4FDD\u5B58</button>
      <button class="mb-btn ghost" data-tlcancel>\u53D6\u6D88</button>
    </div>`;
    const ta = card.querySelector(".tl-edit");
    ta?.focus();
    ta?.addEventListener("keydown", (ev) => {
      if ((ev.ctrlKey || ev.metaKey) && ev.key === "Enter") {
        ev.preventDefault();
        card.querySelector("[data-tlsave]")?.click();
      }
    });
    card.querySelector("[data-tlcancel]").onclick = () => {
      void this.render();
    };
    card.querySelector("[data-tlsave]").onclick = async () => {
      const val = card.querySelector(".tl-edit")?.value ?? "";
      await this.plugin.saveNote(path, val);
      new import_obsidian2.Notice("\u5DF2\u4FDD\u5B58\uFF1A" + path.split("/").pop());
      void this.render();
    };
  }
  /* ---------- 事件绑定 ---------- */
  wire(kanban) {
    const plugin = this.plugin;
    kanban.querySelectorAll("[data-k]").forEach((el) => {
      el.onclick = () => {
        this.kanbanTab = el.dataset.k;
        void this.render();
      };
    });
    kanban.querySelectorAll("[data-newfile]").forEach((el) => {
      el.onclick = () => {
        void plugin.quickCreate(el.dataset.newfile);
      };
    });
    kanban.querySelectorAll("[data-spacestatus]").forEach((el) => {
      el.onclick = () => {
        plugin.setSpaceStatus(el.dataset.spacename, el.dataset.spacestatus);
        void this.render();
      };
    });
    kanban.querySelectorAll("[data-tpledit]").forEach((el) => {
      el.onclick = () => plugin.openFilePath(el.dataset.tpledit);
    });
    kanban.querySelectorAll("[data-needtpl]").forEach((el) => {
      el.onclick = () => {
        const path = el.dataset.needtpl;
        confirmModal(
          plugin,
          `\u300C${path}\u300D\u6A21\u677F\u7F3A\u5931\uFF0C\u662F\u5426\u65B0\u5EFA\uFF1F`,
          () => void plugin.createMissingTemplate(path)
        );
      };
    });
    kanban.querySelectorAll("[data-move]").forEach((el) => {
      el.onclick = () => {
        plugin.moveTab(el.dataset.move, el.dataset.dir);
        void this.render();
      };
    });
    kanban.querySelectorAll("[data-hide]").forEach((el) => {
      el.onclick = () => {
        plugin.toggleHide(el.dataset.hide);
        void this.render();
      };
    });
    kanban.querySelectorAll("[data-adopt]").forEach((el) => {
      el.onclick = () => plugin.openAdoption();
    });
    kanban.querySelectorAll("[data-global-refresh]").forEach((el) => {
      el.onclick = () => {
        void plugin.refreshModel();
        void this.render();
      };
    });
    kanban.querySelectorAll(".scope-tag").forEach((el) => {
      el.onclick = () => {
        plugin.toggleScope(el.dataset.scope);
        void this.render();
      };
    });
    let dragId = null;
    kanban.querySelectorAll("[data-drag]").forEach((el) => {
      el.addEventListener("dragstart", (e) => {
        dragId = el.dataset.drag;
        el.classList.add("dragging");
        try {
          e.dataTransfer.effectAllowed = "move";
        } catch {
        }
      });
      el.addEventListener("dragend", () => {
        el.classList.remove("dragging");
        kanban.querySelectorAll("[data-drag]").forEach((x) => x.classList.remove("dragover"));
      });
      el.addEventListener("dragover", (e) => {
        e.preventDefault();
        el.classList.add("dragover");
      });
      el.addEventListener("dragleave", () => el.classList.remove("dragover"));
      el.addEventListener("drop", (e) => {
        e.preventDefault();
        el.classList.remove("dragover");
        const toId = el.dataset.drag;
        if (!dragId || dragId === toId) return;
        const order = plugin.settings.kanbanOrder;
        const from = order.indexOf(dragId);
        const to = order.indexOf(toId);
        if (from < 0 || to < 0) return;
        order.splice(from, 1);
        order.splice(to, 0, dragId);
        dragId = null;
        void plugin.saveSettings();
        void this.render();
      });
    });
    this.attachHeatmapDrag(kanban);
  }
  attachHeatmapDrag(kanban) {
    const sc = kanban.querySelector("#hmScroll");
    if (!sc) return;
    let down = false, sx = 0, sl = 0;
    sc.addEventListener("pointerdown", (e) => {
      if (e.pointerType !== "mouse") return;
      down = true;
      sx = e.clientX;
      sl = sc.scrollLeft;
    });
    sc.addEventListener("pointermove", (e) => {
      if (!down) return;
      sc.scrollLeft = sl - (e.clientX - sx);
    });
    const end = () => {
      down = false;
    };
    sc.addEventListener("pointerup", end);
    sc.addEventListener("pointerleave", end);
    sc.addEventListener("pointercancel", end);
  }
};
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(plugin, message, onYes) {
    super(plugin.app);
    this.plugin = plugin;
    this.message = message;
    this.onYes = onYes;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u8BF7\u786E\u8BA4" });
    contentEl.createEl("p", { text: this.message, cls: "mb-label" });
    const bar = contentEl.createDiv({
      attr: { style: "margin-top:12px;display:flex;gap:10px;justify-content:flex-end;" }
    });
    const cancel = bar.createEl("button", {
      text: "\u53D6\u6D88",
      cls: "mb-btn ghost"
    });
    cancel.addEventListener("click", () => this.close());
    const yes = bar.createEl("button", {
      text: "\u786E\u5B9A",
      cls: "mb-btn primary"
    });
    yes.addEventListener("click", () => {
      this.onYes();
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
function confirmModal(plugin, message, onYes) {
  new ConfirmModal(plugin, message, onYes).open();
}

// src/adopt.ts
var import_obsidian3 = require("obsidian");
var SKIP_ROOTS = /* @__PURE__ */ new Set([".obsidian", ".trash", ".git"]);
var NEW_SPACE_OPT = "__new_space__";
var CHILD_OPT = "__child__";
var AdoptionModal = class extends import_obsidian3.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.rows = [];
    this.plugin = plugin;
    this.detect();
  }
  // ── 检测：收集所有一级文件夹（排除系统目录与插件自身管理的根目录）──
  detect() {
    const app = this.plugin.app;
    const rn = this.plugin.settings.rootName;
    const skip = new Set(SKIP_ROOTS);
    skip.add(rn);
    skip.add(TEMPLATE_LIBRARY);
    for (const f of app.vault.getAllLoadedFiles()) {
      if (!(f instanceof import_obsidian3.TFolder)) continue;
      if (f.path.includes("/")) continue;
      if (skip.has(f.path)) continue;
      this.rows.push({ path: f.path, name: f.name });
    }
  }
  // 已存在的脑洞空间（用于"单个脑洞"候选，排除自身与系统目录）
  existingSpaces(excludePath) {
    return this.rows.filter((r) => r.path !== excludePath).map((r) => r.name);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u{1F9ED} \u6587\u4EF6\u5939\u6620\u5C04" });
    if (!this.rows.length) {
      contentEl.createEl("p", {
        text: "\u672A\u68C0\u6D4B\u5230\u9700\u8981\u5904\u7406\u7684\u4E00\u7EA7\u6587\u4EF6\u5939\uFF0C\u63D2\u4EF6\u5C06\u6309\u9ED8\u8BA4\u7ED3\u6784\u521D\u59CB\u5316\u3002"
      });
      const bar2 = contentEl.createDiv({ cls: "mb-row end" });
      bar2.createEl("button", { text: "\u5B8C\u6210", cls: "mb-btn" }).addEventListener("click", () => void this.commit([], []));
      return;
    }
    this.rows.forEach((r, i) => this.renderRow(r, i));
    const bar = contentEl.createDiv({ cls: "mb-row end" });
    bar.createEl("button", { text: "\u53D6\u6D88", cls: "mb-btn ghost" }).addEventListener("click", () => this.close());
    bar.createEl("button", { text: "\u786E\u8BA4", cls: "mb-btn" }).addEventListener("click", () => this.confirm());
  }
  // ── 渲染一行：名称 + 保留 / 删除 / 映射至（级联路径选择） ──
  renderRow(r, i) {
    const row = this.contentEl.createDiv({ cls: "adopt-row" });
    row.createSpan({ text: r.name, cls: "adopt-name" });
    const grp = row.createDiv({ cls: "adopt-opts" });
    grp.createEl("label").createEl("input", {
      type: "radio",
      attr: { name: `row${i}`, value: "keep", checked: true }
    }).parentElement.appendText(" \u4FDD\u7559");
    grp.createEl("label").createEl("input", {
      type: "radio",
      attr: { name: `row${i}`, value: "delete" }
    }).parentElement.appendText(" \u5220\u9664\uFF08\u56DE\u6536\u7AD9\uFF09");
    const mapLabel = grp.createEl("label");
    mapLabel.createEl("input", {
      type: "radio",
      attr: { name: `row${i}`, value: "map" }
    });
    mapLabel.appendText(" \u6620\u5C04\u81F3 ");
    const cascade = row.createDiv({ cls: "adopt-map" });
    cascade.style.display = "none";
    const catSel = cascade.createEl("select", {
      cls: "adopt-sel adopt-cat",
      attr: { id: `cat${i}` }
    });
    for (const c of ["\u7075\u611F\u6536\u96C6", "\u5355\u4E2A\u8111\u6D1E", "\u6A21\u677F\u5E93"]) {
      catSel.createEl("option", { text: c, value: c });
    }
    const branch = cascade.createEl("div", {
      cls: "adopt-branch",
      attr: { id: `branch${i}` }
    });
    const renderBranch = () => {
      branch.empty();
      const cat = catSel.value;
      if (cat === "\u7075\u611F\u6536\u96C6") {
        const sel = branch.createEl("select", {
          cls: "adopt-sel",
          attr: { id: `lc_sub${i}` }
        });
        sel.createEl("option", { text: "\u4F5C\u4E3A\u5B50\u6587\u4EF6\u5939", value: CHILD_OPT });
        for (const s of INSP_SUBFOLDERS) {
          sel.createEl("option", { text: s, value: s });
        }
      } else if (cat === "\u6A21\u677F\u5E93") {
        const sel = branch.createEl("select", {
          cls: "adopt-sel",
          attr: { id: `lib_sub${i}` }
        });
        sel.createEl("option", { text: "\u4F5C\u4E3A\u5B50\u6587\u4EF6\u5939", value: CHILD_OPT });
      } else {
        const spSel = branch.createEl("select", {
          cls: "adopt-sel adopt-cat",
          attr: { id: `sp_sel${i}` }
        });
        for (const s of this.existingSpaces(r.path)) {
          spSel.createEl("option", { text: s, value: s });
        }
        spSel.createEl("option", { text: "\uFF0B\u65B0\u5EFA\u8111\u6D1E\u2026", value: NEW_SPACE_OPT });
        const nameInput = branch.createEl("input", {
          type: "text",
          cls: "adopt-name-input",
          attr: { id: `sp_new${i}`, placeholder: "\u65B0\u8111\u6D1E\u540D\u79F0" }
        });
        nameInput.value = r.name;
        nameInput.style.display = "none";
        const subSel = branch.createEl("select", {
          cls: "adopt-sel",
          attr: { id: `sp_sub${i}` }
        });
        subSel.createEl("option", { text: "\u4F5C\u4E3A\u5B50\u6587\u4EF6\u5939", value: CHILD_OPT });
        for (const s of STANDARD) {
          subSel.createEl("option", { text: s, value: s });
        }
        spSel.addEventListener("change", () => {
          nameInput.style.display = spSel.value === NEW_SPACE_OPT ? "" : "none";
        });
      }
    };
    renderBranch();
    catSel.addEventListener("change", renderBranch);
    grp.querySelectorAll("input[type=radio]").forEach((radio) => {
      radio.addEventListener("change", () => {
        cascade.style.display = radio.value === "map" ? "flex" : "none";
      });
    });
  }
  // ── 读取某一行的映射计划 ──
  readPlan(i, r) {
    const cat = this.contentEl.querySelector(`#cat${i}`)?.value;
    if (cat === "\u7075\u611F\u6536\u96C6") {
      const sub2 = this.contentEl.querySelector(`#lc_sub${i}`).value;
      if (sub2 === CHILD_OPT) {
        return {
          from: r.path,
          kind: "child",
          parent: this.plugin.settings.rootName
        };
      }
      return {
        from: r.path,
        kind: "merge",
        parent: this.plugin.settings.rootName,
        sub: sub2
      };
    }
    if (cat === "\u6A21\u677F\u5E93") {
      return { from: r.path, kind: "child", parent: TEMPLATE_LIBRARY };
    }
    const spVal = this.contentEl.querySelector(`#sp_sel${i}`).value;
    const sub = this.contentEl.querySelector(`#sp_sub${i}`).value;
    if (spVal === NEW_SPACE_OPT) {
      const nm = (this.contentEl.querySelector(`#sp_new${i}`).value || "").trim() || r.name;
      const plan2 = {
        from: r.path,
        kind: sub === CHILD_OPT ? "child" : "merge",
        parent: nm,
        newSpace: nm
      };
      if (sub !== CHILD_OPT) plan2.sub = sub;
      return plan2;
    }
    const plan = {
      from: r.path,
      kind: sub === CHILD_OPT ? "child" : "merge",
      parent: spVal
    };
    if (sub !== CHILD_OPT) plan.sub = sub;
    return plan;
  }
  // ── 收集用户选择 ──
  confirm() {
    const deletions = [];
    const maps = [];
    for (let i = 0; i < this.rows.length; i++) {
      const v = this.contentEl.querySelector(
        `input[name="row${i}"]:checked`
      )?.value;
      if (v === "delete") {
        deletions.push(this.rows[i].path);
      } else if (v === "map") {
        const plan = this.readPlan(i, this.rows[i]);
        if (plan) maps.push(plan);
      }
    }
    if (deletions.length) {
      this.showDanger(deletions, maps);
      return;
    }
    void this.commit(maps, deletions);
  }
  // ── 危险确认页（删除操作）──
  showDanger(deletions, maps) {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u26A0\uFE0F \u786E\u8BA4\u5220\u9664" });
    const warn = contentEl.createEl("p", { cls: "mb-danger" });
    warn.textContent = `\u4EE5\u4E0B ${deletions.length} \u4E2A\u6587\u4EF6\u5939\u5C06\u88AB\u79FB\u5165 Obsidian \u56DE\u6536\u7AD9\uFF08.trash\uFF0C\u53EF\u6062\u590D\uFF0C\u975E\u6C38\u4E45\u5220\u9664\uFF09\u3002\u8BF7\u786E\u8BA4\u4F60\u786E\u5B9E\u8981\u79FB\u9664\u5B83\u4EEC\uFF1A`;
    const list = contentEl.createEl("div", { cls: "adopt-del-list" });
    for (const p of deletions) list.createEl("div", { text: p });
    const bar = contentEl.createDiv({ cls: "mb-row end" });
    bar.createEl("button", { text: "\u8FD4\u56DE", cls: "mb-btn ghost" }).addEventListener("click", () => this.onOpen());
    bar.createEl("button", { text: "\u786E\u8BA4\u5220\u9664\u5E76\u63A5\u5165", cls: "mb-btn danger" }).addEventListener("click", () => void this.commit(maps, deletions));
  }
  // ── 执行：删除 + 映射 ──
  async commit(maps, deletions) {
    const app = this.plugin.app;
    for (const d of deletions) {
      const f = app.vault.getAbstractFileByPath(d);
      if (f) {
        try {
          await app.vault.trash(f, true);
        } catch {
        }
      }
    }
    for (const m of maps) {
      const src = app.vault.getAbstractFileByPath(m.from);
      if (!(src instanceof import_obsidian3.TFolder)) continue;
      if (m.newSpace) {
        const sp = m.newSpace;
        await this.plugin.ensureFolder(sp);
        for (const s of STANDARD) {
          await this.plugin.ensureFolder(`${sp}/${s}`);
        }
        await this.plugin.ensureTemplateFiles(sp);
      }
      const targetPath = m.kind === "child" ? `${m.parent}/${src.name}` : `${m.parent}/${m.sub}`;
      if (m.kind === "child" && !app.vault.getAbstractFileByPath(targetPath)) {
        try {
          await app.vault.rename(src, targetPath);
        } catch {
        }
        continue;
      }
      let target = app.vault.getAbstractFileByPath(targetPath);
      if (!target) {
        try {
          await app.vault.createFolder(targetPath);
          target = app.vault.getAbstractFileByPath(targetPath);
        } catch {
        }
      }
      if (target instanceof import_obsidian3.TFolder) {
        await this.moveChildrenInto(src, target);
        try {
          await app.vault.trash(src, false);
        } catch {
        }
      }
    }
    this.plugin.settings.initialized = true;
    await this.plugin.saveSettings();
    try {
      await this.plugin.ensureStructure();
    } catch {
    }
    this.plugin.model = await this.plugin.refreshModel();
    this.plugin.renderOpenView();
    new import_obsidian3.Notice("Meowbius_S.S\uFF1A\u6587\u4EF6\u5939\u6620\u5C04\u5B8C\u6210");
    this.close();
  }
  /** 将 src 内的所有文件/子文件夹移入 target */
  async moveChildrenInto(src, target) {
    const children = [...src.children || []];
    for (const child of children) {
      try {
        const newPath = `${target.path}/${child.name}`;
        if (this.plugin.app.vault.getAbstractFileByPath(newPath)) continue;
        await this.plugin.app.vault.rename(child, newPath);
      } catch {
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/revision.ts
var MAX_HISTORY = 60;
function ensureRecord(revs, path, chars, created) {
  if (!revs[path]) {
    revs[path] = {
      created,
      chars,
      history: [{ t: created, add: chars, del: 0, sn: "\uFF08\u521B\u5EFA\uFF09" }]
    };
  }
  return revs[path];
}
function recordModify(revs, path, newChars, sn, now) {
  let rec = revs[path];
  if (!rec) {
    rec = { created: now, chars: newChars, history: [] };
  }
  const add = Math.max(0, newChars - rec.chars);
  const del = Math.max(0, rec.chars - newChars);
  if (add > 0 || del > 0) {
    rec.history.unshift({ t: now, add, del, sn: sn || "" });
    if (rec.history.length > MAX_HISTORY) rec.history.length = MAX_HISTORY;
  }
  rec.chars = newChars;
  revs[path] = rec;
  return rec;
}

// src/main.ts
var DEFAULT_SETTINGS = {
  rootName: "\u7075\u611F\u6536\u96C6",
  kanbanOrder: [],
  kanbanHidden: {},
  statScope: [...STANDARD],
  spaceStatus: {},
  initialized: false
};
function firstLineSummary(content, max = 40) {
  const lines = content.split("\n").map((l) => l.replace(/^#+\s*/, "").trim()).filter((l) => l.length > 0);
  const s = lines[0] || "\uFF08\u7A7A\u7B14\u8BB0\uFF09";
  return s.length > max ? s.slice(0, max) + "\u2026" : s;
}
var MeowbiusPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = Object.assign({}, DEFAULT_SETTINGS);
    this.revisions = {};
    this.model = null;
    this.refreshTimer = null;
    this.saveTimer = null;
  }
  async onload() {
    try {
      await this.loadSettings();
      this.model = await this.refreshModel();
      await this.bootstrapRevisions();
      if (!this.settings.initialized) {
        this.app.workspace.onLayoutReady(
          () => new AdoptionModal(this).open()
        );
      }
      this.addRibbonIcon("paw-print", "\u6253\u5F00 Meowbius_S.S \u770B\u677F", () => this.openKanban());
      this.registerView(VIEW_TYPE, (leaf) => new KanbanView(leaf, this));
      this.addCommand({
        id: "open-kanban",
        name: "\u6253\u5F00 Meowbius_S.S",
        callback: () => this.openKanban()
      });
      this.addCommand({
        id: "new-space",
        name: "\u65B0\u5EFA\u8111\u6D1E\u7A7A\u95F4",
        callback: () => new NewSpaceModal(this).open()
      });
      this.addCommand({
        id: "capture",
        name: "\u5FEB\u901F\u6355\u6349\uFF1A\u53EA\u8A00\u7247\u8BED",
        callback: () => new CaptureModal(this).open()
      });
      this.addCommand({
        id: "random",
        name: "\u968F\u673A\u7075\u611F",
        callback: () => new RandomModal(this).open()
      });
      this.addCommand({
        id: "revision",
        name: "\u67E5\u770B\u5F53\u524D\u6587\u4EF6\u4FEE\u8BA2\u8BB0\u5F55",
        callback: () => this.openRevision()
      });
      this.addCommand({
        id: "adopt-structure",
        name: "\u6587\u4EF6\u5939\u6620\u5C04",
        callback: () => new AdoptionModal(this).open()
      });
      this.addSettingTab(new MeowbiusSettingTab(this));
      this.registerEvent(
        this.app.vault.on("create", (f) => this.onVaultChange(f))
      );
      this.registerEvent(
        this.app.vault.on("modify", (f) => this.onVaultChange(f))
      );
      this.registerEvent(
        this.app.vault.on("delete", (f) => this.onVaultDelete(f))
      );
    } catch (e) {
      console.error("[Meowbius_S.S] onload error:", e);
      new import_obsidian4.Notice(`Meowbius_S.S \u52A0\u8F7D\u5931\u8D25: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  async onunload() {
    await this.saveRevisionsNow();
  }
  /* ---------------- 数据持久化 ---------------- */
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data && data.settings || {});
    this.revisions = data && data.revisions || {};
    let ss = data && data.settings && data.settings.statScope || [];
    if (typeof ss === "string") ss = [ss];
    const valid = (x) => STANDARD.includes(x) || isTypeFolder(x);
    const isOldDefault = ss.length > 0 && ss.every((x) => STANDARD.includes(x)) && STANDARD.every((x) => ss.includes(x));
    this.settings.statScope = isOldDefault ? [] : ss.filter(valid);
  }
  async saveSettings() {
    await this.saveData({ settings: this.settings, revisions: this.revisions });
  }
  scheduleSaveRevisions() {
    if (this.saveTimer) window.clearTimeout(this.saveTimer);
    this.saveTimer = window.setTimeout(() => {
      void this.saveRevisionsNow();
    }, 1500);
  }
  async saveRevisionsNow() {
    this.saveTimer = null;
    await this.saveData({ settings: this.settings, revisions: this.revisions });
  }
  /* ---------------- 模型与结构 ---------------- */
  async refreshModel() {
    this.model = await buildModel(this.app, this.settings.rootName);
    return this.model;
  }
  renderOpenView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    for (const l of leaves) {
      const v = l.view;
      if (v instanceof KanbanView) void v.render();
    }
  }
  scheduleRefresh() {
    if (this.refreshTimer) window.clearTimeout(this.refreshTimer);
    this.refreshTimer = window.setTimeout(() => {
      void this.refreshModel().then(() => this.renderOpenView());
    }, 400);
  }
  async ensureFolder(path) {
    if (this.app.vault.getAbstractFileByPath(path)) return;
    const slash = path.lastIndexOf("/");
    if (slash > 0) await this.ensureFolder(path.slice(0, slash));
    try {
      await this.app.vault.createFolder(path);
    } catch {
    }
  }
  // 确保某一级目录（灵感收集 / 各脑洞空间）下的「模板」子文件夹与三类模板文件齐备
  async ensureTemplateFiles(primary) {
    for (const type of Object.keys(TPL_FILE)) {
      const fname = TPL_FILE[type];
      const targetPath = `${primary}/\u6A21\u677F/${fname}`;
      if (this.app.vault.getAbstractFileByPath(targetPath)) continue;
      let content = tplContent(type);
      const lib = this.app.vault.getAbstractFileByPath(
        `${TEMPLATE_LIBRARY}/${fname}`
      );
      if (lib instanceof import_obsidian4.TFile) {
        try {
          content = await this.app.vault.cachedRead(lib);
        } catch {
        }
      }
      await this.ensureFolder(`${primary}/\u6A21\u677F`);
      try {
        await this.app.vault.create(targetPath, content);
      } catch {
      }
    }
  }
  async ensureStructure() {
    const rn = this.settings.rootName;
    await this.ensureFolder(rn);
    for (const sub of INSP_SUBFOLDERS) {
      await this.ensureFolder(`${rn}/${sub}`);
    }
    await this.ensureFolder(TEMPLATE_LIBRARY);
    for (const type of Object.keys(TPL_FILE)) {
      const p = `${TEMPLATE_LIBRARY}/${TPL_FILE[type]}`;
      if (!this.app.vault.getAbstractFileByPath(p)) {
        await this.app.vault.create(p, tplContent(type));
      }
    }
    await this.ensureTemplateFiles(rn);
    if (this.model) {
      for (const sp of this.model.spaces) {
        await this.ensureTemplateFiles(sp.path);
      }
    }
  }
  async bootstrapRevisions() {
    const walk = (node) => {
      if (node.type === "note") {
        ensureRecord(
          this.revisions,
          node.path,
          node.words,
          node.created || Date.now()
        );
      } else {
        for (const c of node.children || []) walk(c);
      }
    };
    if (this.model) {
      for (const r of [
        this.model.inspRoot,
        this.model.library,
        ...this.model.spaces
      ]) {
        if (r) walk(r);
      }
    }
    await this.saveRevisionsNow();
  }
  /* ---------------- 仓库事件 ---------------- */
  onVaultChange(file) {
    if (file instanceof import_obsidian4.TFile) {
      this.app.vault.cachedRead(file).then((content) => {
        const chars = content.replace(/\s/g, "").length;
        recordModify(
          this.revisions,
          file.path,
          chars,
          firstLineSummary(content),
          Date.now()
        );
        this.scheduleSaveRevisions();
      }).catch(() => {
      });
    }
    this.scheduleRefresh();
  }
  onVaultDelete(file) {
    if (file instanceof import_obsidian4.TFile) delete this.revisions[file.path];
    this.scheduleRefresh();
  }
  /* ---------------- 看板入口 ---------------- */
  async openKanban() {
    const ws = this.app.workspace;
    const existing = ws.getLeavesOfType(VIEW_TYPE);
    if (existing.length) {
      ws.revealLeaf(existing[0]);
      return;
    }
    const leaf = ws.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
  }
  // 映射当前库中的文件夹（文件夹映射向导，可随时重跑）
  openAdoption() {
    new AdoptionModal(this).open();
  }
  openRevision() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian4.Notice("\u6CA1\u6709\u6B63\u5728\u7F16\u8F91\u7684\u6587\u4EF6");
      return;
    }
    new RevisionModal(this, file).open();
  }
  /* ---------------- 供视图调用的操作 ---------------- */
  async getTemplate(primary, type) {
    const f1 = this.app.vault.getAbstractFileByPath(
      `${primary}/\u6A21\u677F/${TPL_FILE[type]}`
    );
    if (f1 instanceof import_obsidian4.TFile) {
      const c = await this.app.vault.cachedRead(f1);
      if (c.replace(/\s/g, "").length > 0) return c;
    }
    const f2 = this.app.vault.getAbstractFileByPath(
      `${TEMPLATE_LIBRARY}/${TPL_FILE[type]}`
    );
    if (f2 instanceof import_obsidian4.TFile) {
      try {
        return await this.app.vault.cachedRead(f2);
      } catch {
      }
    }
    return tplContent(type);
  }
  async quickCreate(path) {
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!(folder instanceof import_obsidian4.TFolder)) {
      new import_obsidian4.Notice("\u76EE\u6807\u6587\u4EF6\u5939\u4E0D\u5B58\u5728\uFF1A" + path);
      return;
    }
    const parts = path.split("/");
    const primary = parts[0];
    const sub = parts[parts.length - 1];
    const type = templateTypeFor(sub);
    let content = (await this.getTemplate(primary, type)).replace(
      /\{\{date\}\}/g,
      todayStr()
    );
    let base = "\u65B0\u7B14\u8BB0", name = base + ".md", i = 1;
    const existing = (folder.children || []).map((c) => c.name);
    while (existing.includes(name)) name = `${base} ${i++}.md`;
    const file = await this.app.vault.create(`${path}/${name}`, content);
    new import_obsidian4.Notice(`\u5DF2\u5728\u300C${path}\u300D\u65B0\u5EFA\u300C${name}\u300D`);
    await this.app.workspace.getLeaf(true).openFile(file);
  }
  revealPath(path) {
    const af = this.app.vault.getAbstractFileByPath(path);
    if (!af) {
      new import_obsidian4.Notice("\u672A\u627E\u5230\uFF1A" + path);
      return;
    }
    const leaves = this.app.workspace.getLeavesOfType("file-explorer");
    if (leaves.length) {
      try {
        leaves[0].revealInFolder(
          af
        );
      } catch {
      }
    }
    new import_obsidian4.Notice("\u5DF2\u5728\u6587\u4EF6\u680F\u5B9A\u4F4D\uFF1A" + path);
  }
  openFilePath(path) {
    const f = this.app.vault.getAbstractFileByPath(path);
    if (f instanceof import_obsidian4.TFile) void this.app.workspace.getLeaf(true).openFile(f);
  }
  async createMissingTemplate(path) {
    const parts = path.split("/");
    const fname = parts[parts.length - 1];
    const type = Object.keys(TPL_FILE).find((k) => TPL_FILE[k] === fname);
    if (!type) {
      new import_obsidian4.Notice("\u65E0\u6CD5\u8BC6\u522B\u6A21\u677F\u7C7B\u578B");
      return;
    }
    const primary = parts[0];
    await this.ensureFolder(`${primary}/\u6A21\u677F`);
    let content = tplContent(type);
    const lib = this.app.vault.getAbstractFileByPath(
      `${TEMPLATE_LIBRARY}/${fname}`
    );
    if (lib instanceof import_obsidian4.TFile) {
      try {
        content = await this.app.vault.cachedRead(lib);
      } catch {
      }
    }
    await this.app.vault.create(path, content);
    new import_obsidian4.Notice("\u5DF2\u65B0\u5EFA\u6A21\u677F\uFF1A" + path);
    this.openFilePath(path);
  }
  // 供视图使用：聚合热力图数据；prefix 限定只统计某子树（如灵感收集）
  heatmapMap(prefix) {
    const since = /* @__PURE__ */ new Date();
    since.setDate(since.getDate() - 363);
    const sinceMs = since.getTime();
    const map = /* @__PURE__ */ new Map();
    for (const [path, rec] of Object.entries(this.revisions)) {
      if (prefix && !path.startsWith(prefix)) continue;
      for (const e of rec.history) {
        if (e.t < sinceMs || e.add <= 0) continue;
        const d = new Date(e.t);
        const key = `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`;
        map.set(key, (map.get(key) || 0) + e.add);
      }
    }
    return map;
  }
  // 供视图使用：定位节点
  nodeByPath(path) {
    return this.model ? findNode(this.model, path) : void 0;
  }
  /* ---------------- 时间轴（脑洞空间 01_时间轴 文件夹） ---------------- */
  // 取某脑洞空间下「时间轴」类型文件夹的路径（按核心词匹配，兼容任意前缀命名）
  async timelineFolderPath(spacePath) {
    const node = this.nodeByPath(spacePath);
    if (!node) return void 0;
    const core = normalizeName(STANDARD[1]);
    const child = (node.children || []).find(
      (c) => c.type === "folder" && normalizeName(c.name) === core
    );
    return child?.path;
  }
  // 读取时间轴节点（按文件名数字前缀升序）
  async loadTimelineEntries(spacePath) {
    const tlPath = await this.timelineFolderPath(spacePath);
    if (!tlPath) return [];
    const folder = this.app.vault.getAbstractFileByPath(tlPath);
    if (!(folder instanceof import_obsidian4.TFolder)) return [];
    const files = (folder.children || []).filter(
      (c) => c instanceof import_obsidian4.TFile
    );
    const entries = [];
    for (const f of files) {
      let content = "";
      try {
        content = await this.app.vault.cachedRead(f);
      } catch {
        content = "";
      }
      const body = content.replace(/^---\n[\s\S]*?\n---\n?/, "").replace(/[#>*`\-]/g, "").replace(/\s+/g, " ").trim();
      const title = f.name.replace(/^(\d+)[._\-\s]*/, "").replace(/\.md$/i, "");
      entries.push({
        path: f.path,
        name: f.name,
        title: title || f.name,
        mtime: f.stat.mtime,
        words: content.replace(/\s/g, "").length,
        snippet: body.slice(0, 120)
      });
    }
    entries.sort((a, b) => {
      const na = parseInt((a.name.match(/^(\d+)/) || [])[1] || "NaN", 10);
      const nb = parseInt((b.name.match(/^(\d+)/) || [])[1] || "NaN", 10);
      if (!isNaN(na) && !isNaN(nb)) return na - nb;
      if (!isNaN(na)) return -1;
      if (!isNaN(nb)) return 1;
      return a.name.localeCompare(b.name);
    });
    return entries;
  }
  // 读取单条笔记完整内容（供内联编辑预填）
  async readNote(path) {
    const f = this.app.vault.getAbstractFileByPath(path);
    if (f instanceof import_obsidian4.TFile) {
      try {
        return await this.app.vault.cachedRead(f);
      } catch {
        return "";
      }
    }
    return "";
  }
  // 保存单条笔记内容
  async saveNote(path, content) {
    const f = this.app.vault.getAbstractFileByPath(path);
    if (f instanceof import_obsidian4.TFile) await this.app.vault.modify(f, content);
  }
  // 在时间轴文件夹中新建一个节点（自动递增数字前缀）
  async quickCreateTimeline(spacePath) {
    let tlPath = await this.timelineFolderPath(spacePath);
    if (!tlPath) {
      tlPath = `${spacePath}/${STANDARD[1]}`;
      try {
        await this.app.vault.createFolder(tlPath);
      } catch {
      }
    }
    const folder = this.app.vault.getAbstractFileByPath(tlPath);
    if (!(folder instanceof import_obsidian4.TFolder)) {
      new import_obsidian4.Notice("\u65E0\u6CD5\u5B9A\u4F4D\u65F6\u95F4\u8F74\u6587\u4EF6\u5939\uFF1A" + tlPath);
      return;
    }
    const existing = (folder.children || []).filter((c) => c instanceof import_obsidian4.TFile).map((c) => c.name);
    let max = 0;
    for (const n of existing) {
      const m = n.match(/^(\d+)/);
      if (m) max = Math.max(max, parseInt(m[1], 10));
    }
    const prefix = String(max + 1).padStart(4, "0");
    let name = `${prefix}_\u65B0\u8282\u70B9.md`;
    let i = 1;
    while (existing.includes(name)) name = `${prefix}_\u65B0\u8282\u70B9_${i++}.md`;
    const content = `---
\u65F6\u95F4: 
---

# \u65B0\u8282\u70B9

`;
    try {
      await this.app.vault.create(`${tlPath}/${name}`, content);
      new import_obsidian4.Notice(`\u5DF2\u65B0\u5EFA\u65F6\u95F4\u8282\u70B9\uFF1A${name}`);
      this.renderOpenView();
    } catch {
      new import_obsidian4.Notice("\u65B0\u5EFA\u65F6\u95F4\u8282\u70B9\u5931\u8D25");
    }
  }
  // 当前仓库中所有「类型」名（STANDARD ∪ 各脑洞下 数字_文字 子文件夹）
  allTypeNames() {
    const set = new Set(STANDARD);
    const m = this.model;
    if (m) {
      for (const s of m.spaces) {
        for (const t of spaceTypes(s)) set.add(t.name);
      }
    }
    return [...set];
  }
  // 看板配置读写：statScope 为「排除列表」
  // 点击语义：当前全计入（空）→ 切到显式排除模式并排除该类型；
  //           否则在排除集中增删该项；清空后恢复「计入全部类型」。
  toggleScope(type) {
    const all = this.allTypeNames();
    const s = this.settings.statScope.slice();
    if (s.length === 0) {
      this.settings.statScope = all.filter((n) => n !== type);
    } else if (s.includes(type)) {
      this.settings.statScope = s.filter((x) => x !== type);
    } else {
      this.settings.statScope = [...s, type];
    }
    void this.saveSettings();
  }
  moveTab(id, dir) {
    const order = this.settings.kanbanOrder;
    const i = order.indexOf(id);
    if (i < 0) return;
    const j = dir === "up" ? i - 1 : i + 1;
    if (j < 0 || j >= order.length) return;
    const tmp = order[i];
    order[i] = order[j];
    order[j] = tmp;
    void this.saveSettings();
  }
  toggleHide(id) {
    this.settings.kanbanHidden[id] = !this.settings.kanbanHidden[id];
    void this.saveSettings();
  }
  setSpaceStatus(name, status) {
    this.settings.spaceStatus[name] = status;
    void this.saveSettings();
  }
};
var NewSpaceModal = class extends import_obsidian4.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u2728 \u65B0\u5EFA\u8111\u6D1E\u7A7A\u95F4" });
    new import_obsidian4.Setting(contentEl).setName("\u8111\u6D1E\u7A7A\u95F4\u540D\u79F0\uFF08\u6839\u76EE\u5F55\u4E0B\u6587\u4EF6\u5939\u540D\uFF09").addText((t) => {
      this.nameEl = t.inputEl;
      t.setPlaceholder("\u4F8B\u5982\uFF1A\u8D5B\u535A\u957F\u5B89 / \u6DF1\u6D77\u604B\u4EBA");
      t.inputEl.addEventListener("input", () => this.updatePreview());
    });
    new import_obsidian4.Setting(contentEl).setName("\u5C06\u5728\u6839\u76EE\u5F55\u521B\u5EFA\uFF08\u6807\u51C6\u8111\u6D1E\uFF1A7 \u4E2A\u5B50\u6587\u4EF6\u5939 + \u6A21\u677F\uFF09").addText(() => {
    });
    this.previewEl = contentEl.createEl("pre", { cls: "mb-struct" });
    new import_obsidian4.Setting(contentEl).addButton(
      (b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close())
    ).addButton(
      (b) => b.setButtonText("\u521B\u5EFA").setCta().onClick(() => this.create())
    );
    this.updatePreview();
  }
  updatePreview() {
    const name = (this.nameEl?.value || "").trim() || "\u3008\u8111\u6D1E\u540D\u3009";
    const subs = STANDARD;
    let s = `${name}/
`;
    subs.forEach((sub) => s += `  \u{1F4C1} ${sub}/
`);
    s += `  \u{1F4C1} \u6A21\u677F/
`;
    this.previewEl.textContent = s;
  }
  async create() {
    const name = (this.nameEl?.value || "").trim();
    if (!name) {
      new import_obsidian4.Notice("\u8BF7\u5148\u8F93\u5165\u8111\u6D1E\u7A7A\u95F4\u540D\u79F0");
      return;
    }
    const rn = this.plugin.settings.rootName;
    if (name === rn || name === TEMPLATE_LIBRARY) {
      new import_obsidian4.Notice("\u8BE5\u540D\u79F0\u4E0E\u7CFB\u7EDF\u76EE\u5F55\u51B2\u7A81");
      return;
    }
    if (this.plugin.app.vault.getAbstractFileByPath(name)) {
      new import_obsidian4.Notice("\u5DF2\u5B58\u5728\u540C\u540D\u8111\u6D1E\u7A7A\u95F4");
      return;
    }
    const subs = STANDARD;
    await this.plugin.ensureFolder(name);
    for (const sub of subs) await this.plugin.ensureFolder(`${name}/${sub}`);
    await this.plugin.ensureTemplateFiles(name);
    new import_obsidian4.Notice("\u5DF2\u521B\u5EFA\u8111\u6D1E\u7A7A\u95F4\u300C" + name + "\u300D");
    this.close();
    await this.plugin.refreshModel();
    await this.plugin.openKanban();
    this.plugin.renderOpenView();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CaptureModal = class extends import_obsidian4.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u26A1 \u5FEB\u901F\u6355\u6349\uFF1A\u53EA\u8A00\u7247\u8BED" });
    new import_obsidian4.Setting(contentEl).setName("\u5B58\u5165\u4F4D\u7F6E").addDropdown((d) => {
      this.targetEl = d.selectEl;
      const model = this.plugin.model;
      if (model?.inspRoot) {
        const f = model.inspRoot.children?.find(
          (c) => c.type === "folder" && normalizeName(c.name) === normalizeName(STANDARD[3])
        );
        if (f) d.addOption(f.path, `${model.rootName} / ${f.name}`);
      }
      for (const sp of model?.spaces || []) {
        const f = sp.children?.find(
          (c) => c.type === "folder" && normalizeName(c.name) === normalizeName(STANDARD[3])
        );
        if (f) d.addOption(f.path, `${sp.name} / ${f.name}`);
      }
    });
    new import_obsidian4.Setting(contentEl).setName("\u5185\u5BB9").addTextArea((t) => {
      this.textEl = t.inputEl;
      t.setPlaceholder("\u7075\u5149\u4E00\u73B0\uFF0C\u5148\u8BB0\u4E0B\u6765\u518D\u8BF4\u2026");
      t.inputEl.rows = 5;
    });
    new import_obsidian4.Setting(contentEl).addButton((b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close())).addButton(
      (b) => b.setButtonText("\u4FDD\u5B58\u788E\u7247").setCta().onClick(() => this.save())
    );
  }
  async save() {
    const target = this.targetEl?.value;
    const text = (this.textEl?.value || "").trim();
    if (!target) {
      new import_obsidian4.Notice("\u8BF7\u9009\u62E9\u5B58\u5165\u4F4D\u7F6E");
      return;
    }
    if (!text) {
      new import_obsidian4.Notice("\u5199\u70B9\u4EC0\u4E48\u518D\u4FDD\u5B58\u5427");
      return;
    }
    const d = /* @__PURE__ */ new Date();
    const fname = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(
      2,
      "0"
    )}-${String(d.getDate()).padStart(2, "0")}-\u788E\u7247.md`;
    const folder = this.plugin.app.vault.getAbstractFileByPath(target);
    if (!(folder instanceof import_obsidian4.TFolder)) {
      new import_obsidian4.Notice("\u76EE\u6807\u6587\u4EF6\u5939\u4E0D\u5B58\u5728");
      return;
    }
    const existing = (folder.children || []).map((c) => c.name);
    let name = fname, i = 1;
    while (existing.includes(name)) name = `\u788E\u7247 ${i++}.md`;
    const file = await this.plugin.app.vault.create(
      `${target}/${name}`,
      text
    );
    new import_obsidian4.Notice("\u5DF2\u5B58\u5165\u300C" + target + "\u300D\uFF1A" + name);
    this.close();
    await this.plugin.app.workspace.getLeaf(true).openFile(file);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RandomModal = class extends import_obsidian4.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  collect() {
    const res = [];
    const model = this.plugin.model;
    if (!model) return res;
    const pushFrom = (node, space) => {
      const z = node.children?.find(
        (c) => c.type === "folder" && normalizeName(c.name) === normalizeName(STANDARD[3])
      );
      for (const n of z?.children || []) {
        if (n.type === "note") res.push({ space, name: n.name, content: "" });
      }
    };
    if (model.inspRoot) pushFrom(model.inspRoot, model.rootName);
    for (const sp of model.spaces) pushFrom(sp, sp.name);
    return res;
  }
  async draw() {
    const all = this.collect();
    if (!all.length) {
      new import_obsidian4.Notice("\u8FD8\u6CA1\u6709\u53EA\u8A00\u7247\u8BED\u53EF\u968F\u673A");
      return;
    }
    const pick = all[Math.floor(Math.random() * all.length)];
    const file = this.plugin.app.vault.getAbstractFileByPath(
      `${this.pickPath(pick)}`
    );
    let content = "\uFF08\u7A7A\u7B14\u8BB0\uFF09";
    if (file instanceof import_obsidian4.TFile) {
      try {
        content = await this.plugin.app.vault.cachedRead(file);
      } catch {
      }
    }
    this.fromEl.textContent = `\u6765\u81EA\uFF1A\u300C${pick.space} / \u53EA\u8A00\u7247\u8BED\u300D\xB7 ${pick.name}`;
    this.contentEl2.textContent = content;
  }
  pickPath(pick) {
    return `${pick.space}/\u53EA\u8A00\u7247\u8BED/${pick.name}`;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u{1F3B2} \u968F\u673A\u7075\u611F" });
    this.fromEl = contentEl.createDiv({ cls: "mb-label" });
    this.contentEl2 = contentEl.createDiv({
      attr: { style: "white-space:pre-wrap;line-height:1.7;" }
    });
    const bar = contentEl.createDiv({
      attr: { style: "margin-top:14px;display:flex;gap:10px;justify-content:flex-end;" }
    });
    const closeBtn = bar.createEl("button", { text: "\u5173\u95ED", cls: "mb-btn ghost" });
    closeBtn.addEventListener("click", () => this.close());
    const again = bar.createEl("button", { text: "\u518D\u62BD\u4E00\u6761", cls: "mb-btn primary" });
    again.addEventListener("click", () => void this.draw());
    void this.draw();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RevisionModal = class extends import_obsidian4.Modal {
  constructor(plugin, file) {
    super(plugin.app);
    this.plugin = plugin;
    this.file = file;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("mb-modal");
    contentEl.createEl("h3", { text: "\u{1F551} \u5F53\u524D\u6587\u4EF6\u4FEE\u8BA2\u8BB0\u5F55" });
    const rec = this.plugin.revisions[this.file.path];
    const created = rec?.created ? new Date(rec.created).toLocaleString("zh-CN") : new Date(this.file.stat.ctime).toLocaleString("zh-CN");
    contentEl.createEl("div", {
      text: `\u6587\u4EF6\uFF1A${this.file.path}`,
      cls: "mb-label"
    });
    contentEl.createEl("div", {
      text: `\u521B\u5EFA\u65F6\u95F4\uFF1A${created}`,
      attr: { style: "font-size:13px;margin:4px 0 10px;" }
    });
    const list = contentEl.createDiv({ cls: "rev-list" });
    const hist = rec?.history || [];
    if (!hist.length) {
      list.createDiv({ text: "\uFF08\u6682\u65E0\u4FEE\u8BA2\u8BB0\u5F55\uFF09", cls: "mb-label" });
    }
    for (const e of hist) {
      const item = list.createDiv({ cls: "rev-item" });
      item.createDiv({
        text: new Date(e.t).toLocaleString("zh-CN"),
        cls: "rt"
      });
      const rd = item.createDiv({ cls: "rd" });
      rd.innerHTML = `<span class="add">\uFF0B${e.add} \u5B57</span> &nbsp; <span class="del">\uFF0D${e.del} \u5B57</span>`;
      item.createDiv({ text: e.sn, cls: "rs" });
    }
    const bar = contentEl.createDiv({
      attr: { style: "margin-top:12px;display:flex;justify-content:flex-end;" }
    });
    const closeBtn = bar.createEl("button", { text: "\u5173\u95ED", cls: "mb-btn ghost" });
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MeowbiusSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Meowbius_S.S \u8BBE\u7F6E" });
    new import_obsidian4.Setting(containerEl).setName("\u7075\u611F\u6536\u96C6\u6839\u76EE\u5F55\u540D").addText(
      (t) => t.setPlaceholder("\u7075\u611F\u6536\u96C6").setValue(this.plugin.settings.rootName).onChange(async (v) => {
        const name = v.trim();
        if (name) {
          this.plugin.settings.rootName = name;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};
